{
 "title": "customer-monitor",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cId",
    "label": "客户id",
    "query": {
     "query": "label_values(online_customer_app,cId)"
    }
   },
   {
    "name": "customerName",
    "label": "客户名称",
    "query": {
     "query": "label_values(online_customer_app{cId=~\"$cId\", appId=~\"$appId\", appName=~\"$customerAppName\"},name)"
    }
   },
   {
    "name": "appId",
    "label": "客户应用id",
    "query": {
     "query": "label_values(online_customer_app{cId=~\"$cId\"},appId)"
    }
   },
   {
    "name": "customerAppName",
    "label": "应用名称",
    "query": {
     "query": "label_values(online_customer_app{cId=~\"$cId\", appId=~\"$appId\"},appName)"
    }
   },
   { "name": "protocol", "label": "协议类型", "query": "smpp, http, cmpp" }
  ]
 },
 "panels": [
  {
   "title": "应用连接信息",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(online_customer_app{cId=~\"$cId\", name=~\"$customerName\", appId=~\"$appId\", appName=~\"$customerAppName\"}) by (name, appName)",
     "legendFormat": "{{name}}-{{appName}}"
    }
   ]
  },
  {
   "title": "节点submit tps信息(1分钟平均)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(customer_submit_total{stat=\"0\"}[1m]))",
     "legendFormat": "总tps"
    },
    {
     "expr": "sum by(nodeName) (rate(customer_submit_total{stat=\"0\"}[1m]))",
     "legendFormat": "{{nodeName}}节点tps"
    }
   ]
  },
  {
   "title": "客户提交TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by(name, appName)(rate(customer_submit_total{cId=~\"$cId\", name=~\"$customerName\", appId=~\"$appId\", appName=~\"$customerAppName\", protocol=~\"$protocol\", stat=\"0\"}[1m]))",
     "legendFormat": "{{name}}-{{appName}}"
    }
   ]
  },
  {
   "title": "DR回执情况",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(name, appName)(increase(customer_deliver_total{cId=~\"$cId\", name=~\"$customerName\", appId=~\"$appId\", appName=~\"$customerAppName\", stat!~\"^timeout$\"}[1m]))\n/\nclamp_min(sum by(name, appName)(increase(customer_deliver_total{cId=~\"$cId\", name=~\"$customerName\", appId=~\"$appId\", appName=~\"$customerAppName\"}[1m])), 1)",
     "legendFormat": "{{appName}}-回执比例"
    },
    {
     "expr": "sum by(name, appName)(increase(customer_deliver_total{cId=~\"$cId\", name=~\"$customerName\", appId=~\"$appId\", appName=~\"$customerAppName\", stat=~\"^(DELIVRD|ACCEPTD)$\"}[1m]))\n/\nsum by(name, appName)(increase(customer_deliver_total{cId=~\"$cId\", name=~\"$customerName\", appId=~\"$appId\", appName=~\"$customerAppName\"}[1m]))",
     "legendFormat": "{{appName}}-成功比例"
    },
    {
     "expr": "sum by(name, appName)(increase(customer_deliver_total{cId=~\"$cId\", name=~\"$customerName\", appId=~\"$appId\", appName=~\"$customerAppName\", stat!~\"^(DELIVRD|ACCEPTD|timeout)$\"}[1m]))\n/\nsum by(name, appName)(increase(customer_deliver_total{cId=~\"$cId\", name=~\"$customerName\", appId=~\"$appId\", appName=~\"$customerAppName\"}[1m]))",
     "legendFormat": "{{appName}}-失败比例"
    },
    {
     "expr": "sum by(name, appName)(increase(customer_deliver_total{cId=~\"$cId\", name=~\"$customerName\", appId=~\"$appId\", appName=~\"$customerAppName\", stat=~\"^timeout$\"}[1m]))\n/\nsum by(name, appName)(increase(customer_deliver_total{cId=~\"$cId\", name=~\"$customerName\", appId=~\"$appId\", appName=~\"$customerAppName\"}[1m]))",
     "legendFormat": "{{appName}}-超时未返回比例"
    }
   ]
  },
  {
   "title": "短信处理耗时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(customer_deliver_duration_ms_bucket{cId=~\"$cId\", name=~\"$customerName\", appId=~\"$appId\", appName=~\"$customerAppName\", protocol=~\"$protocol\"}[$__rate_interval])) by (le, name, appName))",
     "legendFormat": "{{name}}-{{appName}} 95分位"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(customer_deliver_duration_ms_bucket{cId=~\"$cId\", name=~\"$customerName\", appId=~\"$appId\", appName=~\"$customerAppName\", protocol=~\"$protocol\"}[$__rate_interval])) by (le, name, appName))",
     "legendFormat": "{{name}}-{{appName}} 99分位"
    },
    {
     "expr": "rate(customer_deliver_duration_ms_sum{cId=~\"$cId\", name=~\"$customerName\", appId=~\"$appId\", appName=~\"$customerAppName\", protocol=~\"$protocol\"}[$__rate_interval]) / rate(customer_deliver_duration_ms_count{cId=~\"$cId\", name=~\"$customerName\", appId=~\"$appId\", appName=~\"$customerAppName\", protocol=~\"$protocol\"}[$__rate_interval])",
     "legendFormat": "{{name}}-{{appName}} 平均耗时"
    }
   ]
  },
  {
   "title": "请求耗时（反映网络情况）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(customer_request_duration_ms_bucket{cId=~\"$cId\", name=~\"$customerName\", appId=~\"$appId\", appName=~\"$customerAppName\", protocol=~\"$protocol\"}[1m])) by (le, name, appName))",
     "legendFormat": "{{name}}-{{appName}}95分位"
    },
    {
     "expr": "rate(customer_request_duration_ms_sum{cId=~\"$cId\", name=~\"$customerName\", appId=~\"$appId\", appName=~\"$customerAppName\", protocol=~\"$protocol\"}[$__rate_interval]) / rate(customer_request_duration_ms_count{cId=~\"$cId\", name=~\"$customerName\", appId=~\"$appId\", appName=~\"$customerAppName\", protocol=~\"$protocol\"}[$__rate_interval])",
     "legendFormat": "{{name}}-{{appName}}平均耗时"
    }
   ]
  },
  {
   "title": "收到客户DrResp比例",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(name, appName)(increase(customer_deliver_resp_total{cId=~\"$cId\", name=~\"$customerName\", appId=~\"$appId\", appName=~\"$customerAppName\"}[1m]))\n/\nclamp_min(sum by(name, appName)(increase(customer_deliver_total{cId=~\"$cId\", name=~\"$customerName\", appId=~\"$appId\", appName=~\"$customerAppName\", stat!~\"^timeout$\"}[1m])), 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "客户提交失败监控",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(name, appName, stat)(increase(customer_submit_total{cId=~\"$cId\", name=~\"$customerName\", appId=~\"$appId\", appName=~\"$customerAppName\", stat!=\"0\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "客户登陆情况",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(customer_login_total{appId=~\"$appId\"}[$__range])) by (appId, reason)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "客户提交tps（bind级）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(name, appName, connectId)(rate(customer_submit_total{cId=~\"$cId\", name=~\"$customerName\", appId=~\"$appId\", appName=~\"$customerAppName\", stat=\"0\"}[1m]))",
     "legendFormat": "{{appName}}-{{connectId}}"
    }
   ]
  },
  {
   "title": "上行信息",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum by(name, appName)(increase(customer_mo_req_total{cId=~\"$cId\", name=~\"$customerName\", appId=~\"$appId\", appName=~\"$customerAppName\", stat=\"0\"}[1m]))\n/\nclamp_min(sum by(name, appName)(increase(customer_mo_resp_total{cId=~\"$cId\", name=~\"$customerName\", appId=~\"$appId\", appName=~\"$customerAppName\"}[1m])), 1)",
     "legendFormat": "{{name}}-{{appName}}"
    },
    {
     "expr": "sum by(name, appName, stat)(rate(customer_mo_req_total{cId=~\"$cId\", name=~\"$customerName\", appId=~\"$appId\", appName=~\"$customerAppName\"}[1m]))",
     "legendFormat": "{{name}}-{{appName}}"
    }
   ]
  }
 ]
}