{
 "title": "supplier-monitor",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cId",
    "label": "供应商id",
    "query": {
     "query": "label_values(online_supplier_app,cId)"
    }
   },
   {
    "name": "name",
    "label": "供应商名称",
    "query": {
     "query": "label_values(online_supplier_app{cId=~\"$cId\"},name)"
    }
   },
   {
    "name": "appId",
    "label": "供应商应用id",
    "query": {
     "query": "label_values(online_supplier_app{cId=~\"$cId\"},appId)"
    }
   },
   {
    "name": "appName",
    "label": "供应商应用",
    "query": {
     "query": "label_values(online_supplier_app{cId=~\"$cId\", appId=~\"$appId\"},appName)"
    }
   },
   { "name": "protocol", "label": "协议类型", "query": "smpp, http, cmpp" },
   {
    "name": "countryId",
    "label": "国家id",
    "query": {
     "query": "label_values(supplier_submit_total,countryId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "供应商连接信息",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(online_supplier_app{cId=~\"$cId\", name=~\"$name\", appId=~\"$appId\", appName=~\"$appName\"}) by (name, appName)",
     "legendFormat": "{{name}}-{{appName}}"
    }
   ]
  },
  {
   "title": "sender节点tps信息（1分钟平均）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(supplier_submit_total{stat=\"0\"}[1m]))",
     "legendFormat": "总tps"
    },
    {
     "expr": "sum by(nodeName) (rate(supplier_submit_total{stat=\"0\"}[1m]))",
     "legendFormat": "{{nodeName}}节点tps"
    }
   ]
  },
  {
   "title": "提交到供应商tps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by(name, appName)(rate(supplier_submit_total{cId=~\"$cId\", name=~\"$name\", appId=~\"$appId\", appName=~\"$appName\", protocol=~\"$protocol\", stat=\"0\"}[1m]))",
     "legendFormat": "{{name}}-{{appName}}"
    }
   ]
  },
  {
   "title": "收到通道SubmitResp比例",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(name, appName)(rate(supplier_submit_resp_total{cId=~\"$cId\", name=~\"$name\", appId=~\"$appId\", appName=~\"$appName\"}[1m]))\n/\nclamp_min(sum by(name, appName)(rate(supplier_submit_total{cId=~\"$cId\", name=~\"$name\", appId=~\"$appId\", appName=~\"$appName\", stat!~\"^timeout$\"}[1m])), 1)",
     "legendFormat": "{{name}}-{{appName}}"
    }
   ]
  },
  {
   "title": "提交到供应商tps（bind级）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(name, appName,connectId)(rate(supplier_submit_total{cId=~\"$cId\", name=~\"$name\", appId=~\"$appId\", appName=~\"$appName\", stat=\"0\"}[1m]))",
     "legendFormat": "{{appName}}-{{connectId}}"
    }
   ]
  },
  {
   "title": "通道DR回执情况",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(name, appName)(rate(supplier_deliver_total{cId=~\"$cId\", name=~\"$name\", appId=~\"$appId\", appName=~\"$appName\", stat!~\"^timeout$\"}[1m]))\n/\nclamp_min(sum by(name, appName)(rate(supplier_deliver_total{cId=~\"$cId\", name=~\"$name\", appId=~\"$appId\", appName=~\"$appName\"}[1m])), 1)",
     "legendFormat": "{{appName}}回执比例"
    },
    {
     "expr": "sum by(name, appName)(increase(supplier_deliver_total{cId=~\"$cId\", name=~\"$name\", appId=~\"$appId\", appName=~\"$appName\", stat=~\"^timeout$\"}[1m]))\n/\nsum by(name, appName)(increase(supplier_deliver_total{cId=~\"$cId\", name=~\"$name\", appId=~\"$appId\", appName=~\"$appName\"}[1m]))",
     "legendFormat": "{{appName}}超时未返回比例"
    },
    {
     "expr": "sum by(name, appName)(increase(supplier_deliver_total{cId=~\"$cId\", name=~\"$name\", appId=~\"$appId\", appName=~\"$appName\", stat=~\"^(DELIVRD|ACCEPTD)$\"}[1m]))\n/\nsum by(name, appName)(increase(supplier_deliver_total{cId=~\"$cId\", name=~\"$name\", appId=~\"$appId\", appName=~\"$appName\", stat!~\"^timeout$\"}[1m]))",
     "legendFormat": "{{appName}}-成功比例"
    },
    {
     "expr": "sum by(name, appName)(increase(supplier_deliver_total{cId=~\"$cId\", name=~\"$name\", appId=~\"$appId\", appName=~\"$appName\", stat!~\"^(DELIVRD|ACCEPTD|timeout)$\"}[1m]))\n/\nsum by(name, appName)(increase(supplier_deliver_total{cId=~\"$cId\", name=~\"$name\", appId=~\"$appId\", appName=~\"$appName\", stat!~\"^timeout$\"}[1m]))",
     "legendFormat": "{{appName}}-失败比例"
    }
   ]
  },
  {
   "title": "通道DR回执情况（国家级）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(name, appName, countryId)(rate(supplier_deliver_total{cId=~\"$cId\", name=~\"$name\", appId=~\"$appId\", appName=~\"$appName\", stat!~\"^timeout$\"}[1m]))\n/\nclamp_min(sum by(name, appName, countryId)(rate(supplier_deliver_total{cId=~\"$cId\", name=~\"$name\", appId=~\"$appId\", appName=~\"$appName\"}[1m])), 1)",
     "legendFormat": "{{appName}}{{countryId}}回执比例"
    },
    {
     "expr": "sum by(name, appName, countryId)(increase(supplier_deliver_total{cId=~\"$cId\", name=~\"$name\", appId=~\"$appId\", appName=~\"$appName\", countryId=~\"$countryId\", stat=~\"^timeout$\"}[1m]))\n/\nsum by(name, appName, countryId)(increase(supplier_deliver_total{cId=~\"$cId\", name=~\"$name\", appId=~\"$appId\", appName=~\"$appName\", countryId=~\"$countryId\"}[1m]))",
     "legendFormat": "{{appName}}{{countryId}}超时未返回比例"
    },
    {
     "expr": "sum by(name, appName, countryId)(increase(supplier_deliver_total{cId=~\"$cId\", name=~\"$name\", appId=~\"$appId\", appName=~\"$appName\", countryId=~\"$countryId\", stat=~\"^(DELIVRD|ACCEPTD)$\"}[1m]))\n/\nsum by(name, appName, countryId)(increase(supplier_deliver_total{cId=~\"$cId\", name=~\"$name\", appId=~\"$appId\", appName=~\"$appName\", countryId=~\"$countryId\", stat!~\"^timeout$\"}[1m]))",
     "legendFormat": "{{appName}}{{countryId}}成功比例"
    },
    {
     "expr": "sum by(name, appName, countryId)(increase(supplier_deliver_total{cId=~\"$cId\", name=~\"$name\", appId=~\"$appId\", appName=~\"$appName\", countryId=~\"$countryId\", stat!~\"^(DELIVRD|ACCEPTD|timeout)$\"}[1m]))\n/\nsum by(name, appName, countryId)(increase(supplier_deliver_total{cId=~\"$cId\", name=~\"$name\", appId=~\"$appId\", appName=~\"$appName\", countryId=~\"$countryId\", stat!~\"^timeout$\"}[1m]))",
     "legendFormat": "{{appName}}{{countryId}}失败比例"
    }
   ]
  },
  {
   "title": "请求耗时（反映网络情况）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(supplier_request_duration_ms_bucket{cId=~\"$cId\", name=~\"$name\", appId=~\"$appId\", appName=~\"$appName\", protocol=~\"$protocol\"}[$__rate_interval])) by (le, name, appName))",
     "legendFormat": "{{name}}-{{appName}}95分位"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(supplier_request_duration_ms_bucket{cId=~\"$cId\", name=~\"$name\", appId=~\"$appId\", appName=~\"$appName\", protocol=~\"$protocol\"}[$__rate_interval])) by (le, name, appName))",
     "legendFormat": "{{name}}-{{appName}}99分位"
    },
    {
     "expr": "rate(supplier_request_duration_ms_sum{cId=~\"$cId\", name=~\"$name\", appId=~\"$appId\", appName=~\"$appName\", protocol=~\"$protocol\"}[$__rate_interval]) / rate(supplier_request_duration_ms_count{cId=~\"$cId\", name=~\"$name\", appId=~\"$appId\", appName=~\"$appName\", protocol=~\"$protocol\"}[$__rate_interval])",
     "legendFormat": "{{name}}-{{appName}}平均耗时"
    }
   ]
  },
  {
   "title": "通道连接日志",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(supplier_login_total{appId=~\"$appId\", appName=~\"$appName\"}[$__range])) by (appId, appName, reason)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "上行tps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(name, appName)(rate(supplier_mo_total{cId=~\"$cId\", name=~\"$name\", appId=~\"$appId\", appName=~\"$appName\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}